services:
  sample-redis:
    container_name: sample-redis
    image: dockerhub-dockerio.icellmobilsoft.hu/redis:7.0.1-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5